name: Version Tag Build

permissions:
  contents: write
  id-token: write
  packages: write

on:
  push:
    # To limit whether this executes on a specific branch, you must adjust the allowed_branches input.
    # Specifying 'branches' here is a logical 'OR', not a logical 'AND'.
    tags:
      - v2.*

jobs:

  version-tag-build:
    uses: ritterim/public-github-actions/.github/workflows/npm-packages-release-on-tag.yml@v1.2.0
    #uses: ./.github/workflows/npm-packages-release-on-tag.yml
    secrets:
      myget_api_key: ${{ secrets.MYGET_DEPLOY_API_KEY_SECRET }}
    with:
      allowed_branches: |
        master
      npm_package_name: platform-icons
      run_tests: false
